version: "2"
services:
  postgresql:
    image: bitnami/postgresql:11.11.0-debian-10-r59
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: translation
      POSTGRES_USER: translation
      POSTGRES_PASSWORD: translation